### ISSUE TITLE
charm installation error

### ISSUE THREAD

**Issue by reetug11** [sagrawal87/ABE#6]
While running sudo make in Charm-crypto-0.43 directory getting error
sudo make
Setup build/staging directories
set -x
set +x
Building the Charm Framework
/usr/bin/python3 setup.py build  
Extracting in /tmp/tmp82cjmzdb
Traceback (most recent call last):
  File "/home/reetu/Charm-Crypto-0.43/distribute_setup.py", line 150, in use_setuptools
    raise ImportError
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    use_setuptools() #bootstrap installs Distribute if not installed
  File "/home/reetu/Charm-Crypto-0.43/distribute_setup.py", line 152, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/home/reetu/Charm-Crypto-0.43/distribute_setup.py", line 132, in _do_download
    _build_egg(egg, tarball, to_dir)
  File "/home/reetu/Charm-Crypto-0.43/distribute_setup.py", line 105, in _build_egg
    _extractall(tar)
  File "/home/reetu/Charm-Crypto-0.43/distribute_setup.py", line 500, in _extractall
    self.chown(tarinfo, dirpath)
TypeError: chown() missing 1 required positional argument: 'numeric_owner'
Makefile:27: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by sarahsama** [comment]
If you are using Ubuntu 16.06 and python3.5, just change your python to python3.4. It happens to python3.5.

**Comment by rgupta-11** [comment]
> If you are using Ubuntu 16.06 and python3.5, just change your python to python3.4. It happens to python3.5.



installed charm
After running make && pip install . && python samples/main.py getting error

"Traceback (most recent call last):
File "samples/main.py", line 6, in
from charm.toolbox.pairinggroup import PairingGroup,ZR,G1,G2,GT,pair
ImportError: No module named charm.toolbox.pairinggroup"
I think problem is in mapping or python version
pls help
requirements.txt

**Comment by rgupta-11** [comment]
After running  python samples/main.py getting error
Traceback (most recent call last):
  File "samples/main.py", line 7, in <module>
    from ABE.ac17 import AC17CPABE
ImportError: No module named 'ABE'

**Comment by sagrawal87** [comment]
Could you check the version of Python you are using?

**Comment by reetug11** [comment]
It is python 3.5.2

**Comment by sagrawal87** [comment]
Sorry for a very delayed response. Were you able to fix the errors?

**Comment by reetug11** [comment]
I could run the AC17 ans BSW07 scheme, but in Waters11 it is giving error in KeyGen Line 73.
ValueError: invaalid literal for int() with base 10 : 'ONE'
When I changed attr_list to ['1','2','3'], then it is giving error 
IndexError: list index out of range.

**Comment by reetug11** [comment]
> 
> 
> Sorry for a very delayed response. Were you able to fix the errors?

I am able to run the schemes. I need to work on composite order groups and support is not available in charm. Is there any help available to work on jpbc. The reference papers are : "Security and privacy in smart health: Efficient policy-hiding attribute based access control" and "Expressive cpabe with partially hidden access structures".
Pls help.
[2018 - PASH security-and-privacy-in-smart-health.pdf](https://github.com/sagrawal87/ABE/files/6405111/2018.-.PASH.security-and-privacy-in-smart-health.pdf)
[Lai 2012Expressive CP-ABE with partially hidden access structures.pdf](https://github.com/sagrawal87/ABE/files/6405114/Lai.2012Expressive.CP-ABE.with.partially.hidden.access.structures.pdf)

**Comment by sagrawal87** [comment]
Sorry, I don't know if there is any support available for composite order groups in Charm, but the developers of Charm will be able to give you a better answer. You could write to them directly if you like.

**Comment by Sumasrikanth** [comment]
Iam trying to install Charm-Crypto 0.43 using these step from page https://pages.cs.wisc.edu/~ace/install-charm.html on python 3.8.10. Iam getting error shown below...~/Charm-Crypto-0.43$ ./configure.sh && make && sudo make install && sudo ldconfig
Install prefix    /usr/local
data directory    /usr/local/share/charm
binary directory  /usr/local/bin
library directory /usr/local/lib
config directory  /usr/local/etc
Source path       /home/sumalatha/Charm-Crypto-0.43
CFLAGS            -O2 -g 
CHARM_CFLAGS       -m64 -Wall -Wundef -Wwrite-strings -Wmissing-prototypes  -fstack-protector-all -Wendif-labels -Wmissing-include-dirs -Wempty-body -Wnested-externs -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wold-style-declaration -Wold-style-definition -Wtype-limits
LDFLAGS           -m64 
make              make
python            /usr/bin/python3
build_ext options build_ext 
install           install
host CPU          x86_64
wget              /usr/bin/wget
gprof enabled     no
profiler          no
static build      no
-Werror enabled   no
integer module    yes
ecc module        yes
pairing module    yes
disable benchmark no
libm found        yes
libgmp found      yes
libpbc found      yes
libcrypto found   yes
Documentation     no
Setup build/staging directories
set -x
set +x
Building the Charm Framework
/usr/bin/python3 setup.py build  
Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.42.tar.gz
Traceback (most recent call last):
  File "/home/sumalatha/Charm-Crypto-0.43/distribute_setup.py", line 143, in use_setuptools
    raise ImportError
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    use_setuptools() #bootstrap installs Distribute if not installed
  File "/home/sumalatha/Charm-Crypto-0.43/distribute_setup.py", line 145, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/home/sumalatha/Charm-Crypto-0.43/distribute_setup.py", line 123, in _do_download
    tarball = download_setuptools(version, download_base,
  File "/home/sumalatha/Charm-Crypto-0.43/distribute_setup.py", line 193, in download_setuptools
    src = urlopen(url)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: SSL is required
make: *** [Makefile:28: all] Error 1
please help me out

**Comment by ursa-mikail** [comment]
https://github.com/sagrawal87/ABE/issues/6#issuecomment-2126438007
still not solved since May 23? 

Why not placed a caveat as this can waste 1000s of people's time?

```
ERROR: Could not find a version that satisfies the requirement charm-crypto==0.43 (from versions: 0.43)
ERROR: No matching distribution found for charm-crypto==0.43
Traceback (most recent call last):
  File "/content/./ABE/setup.py", line 3, in <module>

Error during import: No module named 'charm.toolbox'
```
